server:
  port: 8080
  servlet:
    context-path: /api/butterfly-service


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/plumemo?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*/auto/*.xml
  type-aliases-package: com.ayding.butterfly.*.dao.auto
  config-location: classpath:config/mybatis-config.xml



logging:
  config: classpath:config/spring-logback.xml