package com.ayding.butterfly.posts.domain.po;

import java.util.Date;

public class PlumemoPosts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.author_id
     *
     * @mbg.generated
     */
    private Long authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.thumbnail
     *
     * @mbg.generated
     */
    private String thumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.comments
     *
     * @mbg.generated
     */
    private Integer comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.is_comment
     *
     * @mbg.generated
     */
    private Short isComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.sync_status
     *
     * @mbg.generated
     */
    private Short syncStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.views
     *
     * @mbg.generated
     */
    private Integer views;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.weight
     *
     * @mbg.generated
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plumemo_posts.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.id
     *
     * @return the value of plumemo_posts.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.id
     *
     * @param id the value for plumemo_posts.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.author_id
     *
     * @return the value of plumemo_posts.author_id
     *
     * @mbg.generated
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.author_id
     *
     * @param authorId the value for plumemo_posts.author_id
     *
     * @mbg.generated
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.title
     *
     * @return the value of plumemo_posts.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.title
     *
     * @param title the value for plumemo_posts.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.thumbnail
     *
     * @return the value of plumemo_posts.thumbnail
     *
     * @mbg.generated
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.thumbnail
     *
     * @param thumbnail the value for plumemo_posts.thumbnail
     *
     * @mbg.generated
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.comments
     *
     * @return the value of plumemo_posts.comments
     *
     * @mbg.generated
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.comments
     *
     * @param comments the value for plumemo_posts.comments
     *
     * @mbg.generated
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.is_comment
     *
     * @return the value of plumemo_posts.is_comment
     *
     * @mbg.generated
     */
    public Short getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.is_comment
     *
     * @param isComment the value for plumemo_posts.is_comment
     *
     * @mbg.generated
     */
    public void setIsComment(Short isComment) {
        this.isComment = isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.category_id
     *
     * @return the value of plumemo_posts.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.category_id
     *
     * @param categoryId the value for plumemo_posts.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.sync_status
     *
     * @return the value of plumemo_posts.sync_status
     *
     * @mbg.generated
     */
    public Short getSyncStatus() {
        return syncStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.sync_status
     *
     * @param syncStatus the value for plumemo_posts.sync_status
     *
     * @mbg.generated
     */
    public void setSyncStatus(Short syncStatus) {
        this.syncStatus = syncStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.status
     *
     * @return the value of plumemo_posts.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.status
     *
     * @param status the value for plumemo_posts.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.summary
     *
     * @return the value of plumemo_posts.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.summary
     *
     * @param summary the value for plumemo_posts.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.views
     *
     * @return the value of plumemo_posts.views
     *
     * @mbg.generated
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.views
     *
     * @param views the value for plumemo_posts.views
     *
     * @mbg.generated
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.weight
     *
     * @return the value of plumemo_posts.weight
     *
     * @mbg.generated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.weight
     *
     * @param weight the value for plumemo_posts.weight
     *
     * @mbg.generated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.create_time
     *
     * @return the value of plumemo_posts.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.create_time
     *
     * @param createTime the value for plumemo_posts.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plumemo_posts.update_time
     *
     * @return the value of plumemo_posts.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plumemo_posts.update_time
     *
     * @param updateTime the value for plumemo_posts.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}