package com.ayding.butterfly.posts.dao.auto;

import com.ayding.butterfly.posts.domain.po.PlumemoPosts;
import com.ayding.butterfly.posts.domain.po.PlumemoPostsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlumemoPostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    long countByExample(PlumemoPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    int deleteByExample(PlumemoPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    int insert(PlumemoPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    int insertSelective(PlumemoPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    List<PlumemoPosts> selectByExample(PlumemoPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    PlumemoPosts selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlumemoPosts record, @Param("example") PlumemoPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlumemoPosts record, @Param("example") PlumemoPostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlumemoPosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plumemo_posts
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlumemoPosts record);
}